// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR-HAN4ywREqsmswgYT4_-XaHYeB0xMys',
    appId: '1:67477397774:web:e12fdc2fe850e73b92b75f',
    messagingSenderId: '67477397774',
    projectId: 'livehealthy-e76f9',
    authDomain: 'livehealthy-e76f9.firebaseapp.com',
    databaseURL: 'https://livehealthy-e76f9-default-rtdb.firebaseio.com',
    storageBucket: 'livehealthy-e76f9.firebasestorage.app',
    measurementId: 'G-T5W3E2B3ER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFLOzhBD6TMzjHMtzuRZdW4wJLfWDLr5A',
    appId: '1:67477397774:android:3132918ee3374fe392b75f',
    messagingSenderId: '67477397774',
    projectId: 'livehealthy-e76f9',
    databaseURL: 'https://livehealthy-e76f9-default-rtdb.firebaseio.com',
    storageBucket: 'livehealthy-e76f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkQnlzaoWw8I0WTAV6za_5jxZOIUNe7hw',
    appId: '1:67477397774:ios:5d52226b1475ec8192b75f',
    messagingSenderId: '67477397774',
    projectId: 'livehealthy-e76f9',
    databaseURL: 'https://livehealthy-e76f9-default-rtdb.firebaseio.com',
    storageBucket: 'livehealthy-e76f9.firebasestorage.app',
    iosBundleId: 'com.example.dlivehealthy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkQnlzaoWw8I0WTAV6za_5jxZOIUNe7hw',
    appId: '1:67477397774:ios:5d52226b1475ec8192b75f',
    messagingSenderId: '67477397774',
    projectId: 'livehealthy-e76f9',
    databaseURL: 'https://livehealthy-e76f9-default-rtdb.firebaseio.com',
    storageBucket: 'livehealthy-e76f9.firebasestorage.app',
    iosBundleId: 'com.example.dlivehealthy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR-HAN4ywREqsmswgYT4_-XaHYeB0xMys',
    appId: '1:67477397774:web:dcbd97d13c4fe02c92b75f',
    messagingSenderId: '67477397774',
    projectId: 'livehealthy-e76f9',
    authDomain: 'livehealthy-e76f9.firebaseapp.com',
    databaseURL: 'https://livehealthy-e76f9-default-rtdb.firebaseio.com',
    storageBucket: 'livehealthy-e76f9.firebasestorage.app',
    measurementId: 'G-8QYW0QGE13',
  );
}
